---

driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: bimble-runner
    data_bags_path: 'test/data_bags'
    run_list:
      - recipe[bimble-runner::default]
